### ISSUE TITLE
module not found in landuse change script

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-esm1.5-configs#67]
This PR https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/66 used a work-around to access the python conda environment that is running `payu`.

This doesn't work because it's not opening a shell, and so doesn't have the `module` infra loaded, and throws this error:
```
./scripts/update_landuse_driver.sh: line 4: module: command not found
Traceback (most recent call last):
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/site-packages/payu/fsops.py", line 320, in _run_script
    subprocess.check_call(shlex.split(script_cmd))
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './scripts/update_landuse_driver.sh'
```

**Comment by aidanheerdegen** [comment]
One possible solution is to force the `bash` interpreter in the update landuse driver script to be a login shell. 

If that doesn't work we can hard-code a path to a released python environment and flag to fix later.

**Comment by jo-basevi** [comment]
With `payu/1.1.6`, it still doesn't support module load in user scripts (see https://github.com/payu-org/payu/issues/522), so it might be worth updating the historical configuration to use the `payu/1.1.6` python executable. This will be `/g/data/vk83/apps/conda_scripts/payu-1.1.6.d/bin/python3` as it needs to launch a container to access python in the payu-1.1.6 conda environment.

**Comment by jo-basevi** [comment]
There is an issue using `#!/g/data/vk83/apps/conda_scripts/payu-1.1.6.d/bin/python3` as the python interpreter when running with the `payu/dev` module. This is because payu now runs inside a container that has a overlay for the `payu-dev` conda environment which makes those files accessible. Then when it tries to run the  `/g/data/vk83/apps/conda_scripts/payu-1.1.6.d/bin/python3` launcher script, as it's already inside a container, it will try to run the `payu-1.1.6` conda environment directly but the `payu-1.1.6` files won't be accessible. 

So I'll revert the changes, back to `#!/g/data/vk83/apps/payu/1.1.5/bin/python` for the `replace_landsurface.py` user-script as those files will be accessible in both `payu/dev` and `payu/1.1.6` modules. 

There's currently a PR to load conda environment in the container launcher scripts (https://github.com/ACCESS-NRI/model-release-condaenv/pull/13), and that will allow `#!/usr/bin/env python3` to be used for payu user-scripts.
